name: Release
on:
  push:
    branches:
      - main

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - uses: actions/checkout@v2
            - name: Get tag version
              id: tag_name
              run: |
                    VERSION=$(grep . /versions | tail -1)
                    echo "Current version: $VERSION"
                    echo "SOURCE_TAG=${VERSION}" >> $GITHUB_OUTPUT
                    
            - name: Get repo name
              id: repo_name
              run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | sed -e "s/:refs//")" >> $GITHUB_OUTPUT
            - name: Build a release
              run: |
               bash create_release.sh $SOURCE_TAG
              env:
               SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               GITHUB_REPO: ${{ steps.repo_name.outputs.REPOSITORY_NAME }}
